#ifndef KRAKEN_LWIPOPTS_H
#define KRAKEN_LWIPOPTS_H

#define LWIP_NETIF_API 1
#define LWIP_COMPAT_SOCKETS 0
#define LWIP_TCPIP_CORE_LOCKING 1
#define LWIP_RAW 1
#define TCP_LISTEN_BACKLOG 1
#define ARP_QUEUEING 1
#define MEM_LIBC_MALLOC 1
#define MEMP_MEM_MALLOC 1
#define MEMP_NUM_NETCONN 256
#define MEMP_NUM_TCP_PCB 256
#define MEMP_NUM_UDP_PCB 256
#define MEMP_NUM_RAW_PCB 64
#define MEM_ALIGNMENT 8

#endif
