// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adoption} from '../models';
import {net} from '../models';
import {buffer} from '../models';
import {storage} from '../models';
import {operations} from '../models';

export function AdoptIPAddress(arg1:adoption.Identity):Promise<adoption.Identity>;

export function AdoptStoredAdoptionConfiguration(arg1:string):Promise<adoption.Identity>;

export function Close():Promise<void>;

export function DeleteStoredAdoptionConfiguration(arg1:string):Promise<void>;

export function DeleteStoredScript(arg1:string):Promise<void>;

export function ForwardFrame(arg1:net.IP,arg2:buffer.Buffer):Promise<boolean>;

export function GetAdoptedIPAddressDetails(arg1:string):Promise<adoption.Identity>;

export function GetStoredScript(arg1:string):Promise<storage.StoredScript>;

export function ListAdoptedIPAddresses():Promise<Array<adoption.Identity>>;

export function ListStoredAdoptionConfigurations():Promise<Array<storage.StoredAdoptionConfiguration>>;

export function ListStoredScripts():Promise<Array<storage.StoredScriptSummary>>;

export function RefreshStoredScripts():Promise<Array<storage.StoredScriptSummary>>;

export function ReleaseIPAddress(arg1:string):Promise<void>;

export function ResolveDNSAdoptedIPAddress(arg1:operations.ResolveDNSAdoptedIPAddressRequest):Promise<operations.ResolveDNSAdoptedIPAddressResult>;

export function SaveStoredAdoptionConfiguration(arg1:string,arg2:storage.StoredAdoptionConfiguration):Promise<storage.StoredAdoptionConfiguration>;

export function SaveStoredScript(arg1:storage.SaveStoredScriptRequest):Promise<storage.StoredScript>;

export function StartAdoptedIPAddressRecording(arg1:string,arg2:string):Promise<adoption.Identity>;

export function StartAdoptedIPAddressService(arg1:string,arg2:string,arg3:Record<string, string>):Promise<adoption.Identity>;

export function StopAdoptedIPAddressRecording(arg1:string):Promise<adoption.Identity>;

export function StopAdoptedIPAddressService(arg1:string,arg2:string):Promise<adoption.Identity>;

export function UpdateAdoptedIPAddressMTU(arg1:string,arg2:number):Promise<adoption.Identity>;

export function UpdateAdoptedIPAddressScript(arg1:string,arg2:string):Promise<adoption.Identity>;
