// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptIPAddress(arg1) {
  return window['go']['adoption']['Manager']['AdoptIPAddress'](arg1);
}

export function Close() {
  return window['go']['adoption']['Manager']['Close']();
}

export function DeleteScript(arg1, arg2) {
  return window['go']['adoption']['Manager']['DeleteScript'](arg1, arg2);
}

export function GetAdoptedIPAddressDetails(arg1) {
  return window['go']['adoption']['Manager']['GetAdoptedIPAddressDetails'](arg1);
}

export function GetScript(arg1, arg2) {
  return window['go']['adoption']['Manager']['GetScript'](arg1, arg2);
}

export function ListAdoptedIPAddresses() {
  return window['go']['adoption']['Manager']['ListAdoptedIPAddresses']();
}

export function ListScripts(arg1) {
  return window['go']['adoption']['Manager']['ListScripts'](arg1);
}

export function PingAdoptedIPAddress(arg1) {
  return window['go']['adoption']['Manager']['PingAdoptedIPAddress'](arg1);
}

export function RefreshScripts(arg1) {
  return window['go']['adoption']['Manager']['RefreshScripts'](arg1);
}

export function ReleaseIPAddress(arg1) {
  return window['go']['adoption']['Manager']['ReleaseIPAddress'](arg1);
}

export function ResolveDNSAdoptedIPAddress(arg1) {
  return window['go']['adoption']['Manager']['ResolveDNSAdoptedIPAddress'](arg1);
}

export function RunStoredGenericScript(arg1) {
  return window['go']['adoption']['Manager']['RunStoredGenericScript'](arg1);
}

export function SaveScript(arg1, arg2) {
  return window['go']['adoption']['Manager']['SaveScript'](arg1, arg2);
}

export function SetGenericScriptOutputSink(arg1) {
  return window['go']['adoption']['Manager']['SetGenericScriptOutputSink'](arg1);
}

export function StartAdoptedIPAddressRecording(arg1, arg2) {
  return window['go']['adoption']['Manager']['StartAdoptedIPAddressRecording'](arg1, arg2);
}

export function StartAdoptedIPAddressService(arg1, arg2, arg3) {
  return window['go']['adoption']['Manager']['StartAdoptedIPAddressService'](arg1, arg2, arg3);
}

export function StopAdoptedIPAddressRecording(arg1) {
  return window['go']['adoption']['Manager']['StopAdoptedIPAddressRecording'](arg1);
}

export function StopAdoptedIPAddressService(arg1, arg2) {
  return window['go']['adoption']['Manager']['StopAdoptedIPAddressService'](arg1, arg2);
}

export function StopStoredGenericScript() {
  return window['go']['adoption']['Manager']['StopStoredGenericScript']();
}

export function UpdateAdoptedIPAddressMTU(arg1, arg2) {
  return window['go']['adoption']['Manager']['UpdateAdoptedIPAddressMTU'](arg1, arg2);
}

export function UpdateAdoptedIPAddressScript(arg1, arg2) {
  return window['go']['adoption']['Manager']['UpdateAdoptedIPAddressScript'](arg1, arg2);
}
