// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adoption} from '../models';
import {storage} from '../models';
import {operations} from '../models';
import {script} from '../models';

export function AdoptIPAddress(arg1:adoption.Identity):Promise<adoption.Identity>;

export function Close():Promise<void>;

export function DeleteScript(arg1:string,arg2:string):Promise<void>;

export function GetAdoptedIPAddressDetails(arg1:string):Promise<adoption.Identity>;

export function GetScript(arg1:string,arg2:string):Promise<storage.StoredScript>;

export function ListAdoptedIPAddresses():Promise<Array<adoption.Identity>>;

export function ListScripts(arg1:string):Promise<Array<storage.StoredScriptSummary>>;

export function PingAdoptedIPAddress(arg1:operations.PingAdoptedIPAddressRequest):Promise<operations.PingAdoptedIPAddressResult>;

export function RefreshScripts(arg1:string):Promise<Array<storage.StoredScriptSummary>>;

export function ReleaseIPAddress(arg1:string):Promise<void>;

export function ResolveDNSAdoptedIPAddress(arg1:operations.ResolveDNSAdoptedIPAddressRequest):Promise<operations.ResolveDNSAdoptedIPAddressResult>;

export function RunStoredGenericScript(arg1:string):Promise<script.RunResult>;

export function SaveScript(arg1:string,arg2:storage.SaveStoredScriptRequest):Promise<storage.StoredScript>;

export function SetGenericScriptOutputSink(arg1:any):Promise<void>;

export function StartAdoptedIPAddressRecording(arg1:string,arg2:string):Promise<adoption.Identity>;

export function StartAdoptedIPAddressService(arg1:string,arg2:string,arg3:Record<string, string>):Promise<adoption.Identity>;

export function StopAdoptedIPAddressRecording(arg1:string):Promise<adoption.Identity>;

export function StopAdoptedIPAddressService(arg1:string,arg2:string):Promise<adoption.Identity>;

export function StopStoredGenericScript():Promise<void>;

export function UpdateAdoptedIPAddressMTU(arg1:string,arg2:number):Promise<adoption.Identity>;

export function UpdateAdoptedIPAddressScript(arg1:string,arg2:string):Promise<adoption.Identity>;
