pub const max_scripts_per_kind = 128;
pub const field_capacity = 128;
pub const source_capacity = 8 * 1024;
pub const runtime_command_capacity = 64;
pub const runtime_issue_capacity = 64;
pub const ui_log_capacity = 256;
pub const ui_signal_capacity = 512;
pub const ui_signal_event_capacity = 256;
pub const storage_scratch_capacity = 512 * 1024;
