// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adoption} from '../models';
import {storage} from '../models';
import {net} from '../models';
import {buffer} from '../models';
import {interfaces} from '../models';
import {operations} from '../models';

export function Adopt(arg1:adoption.Identity,arg2:adoption.Listener):Promise<adoption.Identity>;

export function AdoptIPAddress(arg1:adoption.Identity):Promise<adoption.Identity>;

export function AdoptStoredAdoptionConfiguration(arg1:string):Promise<adoption.Identity>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function Close():Promise<void>;

export function DeleteStoredAdoptionConfiguration(arg1:string):Promise<void>;

export function DeleteStoredScript(arg1:storage.StoredScriptRef):Promise<void>;

export function ForwardFrame(arg1:net.IP,arg2:buffer.Buffer):Promise<boolean>;

export function GetAdoptedIPAddressDetails(arg1:string):Promise<adoption.Identity>;

export function GetConfigurationDirectory():Promise<string>;

export function GetStoredScript(arg1:storage.StoredScriptRef):Promise<storage.StoredScript>;

export function ListAdoptedIPAddresses():Promise<Array<adoption.Identity>>;

export function ListAdoptionInterfaces():Promise<interfaces.Selection>;

export function ListServiceDefinitions():Promise<Array<adoption.ServiceDefinition>>;

export function ListStoredAdoptionConfigurations():Promise<Array<storage.StoredAdoptionConfiguration>>;

export function ListStoredScripts():Promise<Array<storage.StoredScriptSummary>>;

export function Lookup(arg1:net.IP):Promise<adoption.Identity>;

export function RefreshStoredScripts():Promise<Array<storage.StoredScriptSummary>>;

export function Release(arg1:net.IP):Promise<void>;

export function ReleaseIPAddress(arg1:string):Promise<void>;

export function ResolveDNSAdoptedIPAddress(arg1:operations.ResolveDNSAdoptedIPAddressRequest):Promise<operations.ResolveDNSAdoptedIPAddressResult>;

export function SaveStoredAdoptionConfiguration(arg1:storage.StoredAdoptionConfiguration):Promise<storage.StoredAdoptionConfiguration>;

export function SaveStoredScript(arg1:storage.SaveStoredScriptRequest):Promise<storage.StoredScript>;

export function Shutdown():Promise<void>;

export function Snapshot():Promise<Array<adoption.Identity>>;

export function StartAdoptedIPAddressRecording(arg1:adoption.StartAdoptedIPAddressRecordingRequest):Promise<adoption.Identity>;

export function StartAdoptedIPAddressService(arg1:adoption.StartAdoptedIPAddressServiceRequest):Promise<adoption.Identity>;

export function StartConfiguredService(arg1:net.IP,arg2:string,arg3:Record<string, string>):Promise<adoption.Identity>;

export function StartRecording(arg1:net.IP,arg2:string):Promise<adoption.Identity>;

export function StartService(arg1:net.IP,arg2:adoption.ManagedService,arg3:any):Promise<adoption.Identity>;

export function StopAdoptedIPAddressRecording(arg1:string):Promise<adoption.Identity>;

export function StopAdoptedIPAddressService(arg1:adoption.StopAdoptedIPAddressServiceRequest):Promise<adoption.Identity>;

export function StopRecording(arg1:net.IP):Promise<adoption.Identity>;

export function StopService(arg1:net.IP,arg2:string):Promise<adoption.Identity>;

export function UpdateAdoptedIPAddress(arg1:adoption.UpdateAdoptedIPAddressRequest):Promise<adoption.Identity>;

export function UpdateAdoptedIPAddressScripts(arg1:adoption.UpdateAdoptedIPAddressScriptsRequest):Promise<adoption.Identity>;

export function UpdateScripts(arg1:net.IP,arg2:string,arg3:string):Promise<void>;
