// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptIPAddress(arg1) {
  return window['go']['main']['App']['AdoptIPAddress'](arg1);
}

export function AdoptStoredAdoptionConfiguration(arg1) {
  return window['go']['main']['App']['AdoptStoredAdoptionConfiguration'](arg1);
}

export function ClearAdoptedIPAddressActivity(arg1, arg2) {
  return window['go']['main']['App']['ClearAdoptedIPAddressActivity'](arg1, arg2);
}

export function GetAdoptedIPAddressDetails(arg1) {
  return window['go']['main']['App']['GetAdoptedIPAddressDetails'](arg1);
}

export function ListAdoptedIPAddresses() {
  return window['go']['main']['App']['ListAdoptedIPAddresses']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function ListStoredAdoptionConfigurations() {
  return window['go']['main']['App']['ListStoredAdoptionConfigurations']();
}

export function PingAdoptedIPAddress(arg1) {
  return window['go']['main']['App']['PingAdoptedIPAddress'](arg1);
}

export function ReleaseIPAddress(arg1) {
  return window['go']['main']['App']['ReleaseIPAddress'](arg1);
}

export function SaveStoredAdoptionConfiguration(arg1) {
  return window['go']['main']['App']['SaveStoredAdoptionConfiguration'](arg1);
}

export function UpdateAdoptedIPAddress(arg1) {
  return window['go']['main']['App']['UpdateAdoptedIPAddress'](arg1);
}
