// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adoption} from '../models';
import {script} from '../models';
import {interfaces} from '../models';
import {storage} from '../models';

export function AdoptIPAddress(arg1:adoption.AdoptIPAddressRequest):Promise<adoption.AdoptedIPAddress>;

export function AdoptStoredAdoptionConfiguration(arg1:string):Promise<adoption.AdoptedIPAddress>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function DeleteStoredAdoptionConfiguration(arg1:string):Promise<void>;

export function DeleteStoredRoute(arg1:string):Promise<void>;

export function DeleteStoredScript(arg1:script.StoredScriptRef):Promise<void>;

export function GetAdoptedIPAddressDetails(arg1:string):Promise<adoption.AdoptedIPAddressDetails>;

export function GetConfigurationDirectory():Promise<string>;

export function GetStoredScript(arg1:script.StoredScriptRef):Promise<script.StoredScript>;

export function ListAdoptedIPAddresses():Promise<Array<adoption.AdoptedIPAddress>>;

export function ListAdoptionInterfaces():Promise<interfaces.Selection>;

export function ListServiceDefinitions():Promise<Array<adoption.ServiceDefinition>>;

export function ListStoredAdoptionConfigurations():Promise<Array<storage.StoredAdoptionConfiguration>>;

export function ListStoredRoutes():Promise<Array<storage.StoredRoute>>;

export function ListStoredScripts():Promise<Array<script.StoredScriptSummary>>;

export function PingAdoptedIPAddress(arg1:adoption.PingAdoptedIPAddressRequest):Promise<adoption.PingAdoptedIPAddressResult>;

export function RefreshStoredScripts():Promise<Array<script.StoredScriptSummary>>;

export function ReleaseIPAddress(arg1:string):Promise<void>;

export function ResolveDNSAdoptedIPAddress(arg1:adoption.ResolveDNSAdoptedIPAddressRequest):Promise<adoption.ResolveDNSAdoptedIPAddressResult>;

export function SaveStoredAdoptionConfiguration(arg1:storage.StoredAdoptionConfiguration):Promise<storage.StoredAdoptionConfiguration>;

export function SaveStoredRoute(arg1:storage.StoredRoute):Promise<storage.StoredRoute>;

export function SaveStoredScript(arg1:script.SaveStoredScriptRequest):Promise<script.StoredScript>;

export function Shutdown():Promise<void>;

export function StartAdoptedIPAddressRecording(arg1:adoption.StartAdoptedIPAddressRecordingRequest):Promise<adoption.AdoptedIPAddressDetails>;

export function StartAdoptedIPAddressService(arg1:adoption.StartAdoptedIPAddressServiceRequest):Promise<adoption.AdoptedIPAddressDetails>;

export function StopAdoptedIPAddressRecording(arg1:string):Promise<adoption.AdoptedIPAddressDetails>;

export function StopAdoptedIPAddressService(arg1:adoption.StopAdoptedIPAddressServiceRequest):Promise<adoption.AdoptedIPAddressDetails>;

export function UpdateAdoptedIPAddress(arg1:adoption.UpdateAdoptedIPAddressRequest):Promise<adoption.AdoptedIPAddress>;

export function UpdateAdoptedIPAddressScripts(arg1:adoption.UpdateAdoptedIPAddressScriptsRequest):Promise<adoption.AdoptedIPAddressDetails>;
