// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory(arg1) {
  return window['go']['main']['App']['ChooseDirectory'](arg1);
}

export function CopyStoredAdoptionConfiguration(arg1, arg2) {
  return window['go']['main']['App']['CopyStoredAdoptionConfiguration'](arg1, arg2);
}

export function CreateKeytab(arg1) {
  return window['go']['main']['App']['CreateKeytab'](arg1);
}

export function DeleteStoredAdoptionConfiguration(arg1) {
  return window['go']['main']['App']['DeleteStoredAdoptionConfiguration'](arg1);
}

export function GetConfigurationDirectory() {
  return window['go']['main']['App']['GetConfigurationDirectory']();
}

export function ListAdoptionInterfaces() {
  return window['go']['main']['App']['ListAdoptionInterfaces']();
}

export function ListStoredAdoptionConfigurations() {
  return window['go']['main']['App']['ListStoredAdoptionConfigurations']();
}

export function SaveStoredAdoptionConfiguration(arg1) {
  return window['go']['main']['App']['SaveStoredAdoptionConfiguration'](arg1);
}
