// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdoptIPAddress(arg1) {
  return window['go']['main']['ManagerAPI']['AdoptIPAddress'](arg1);
}

export function AdoptStoredAdoptionConfiguration(arg1) {
  return window['go']['main']['ManagerAPI']['AdoptStoredAdoptionConfiguration'](arg1);
}

export function Close() {
  return window['go']['main']['ManagerAPI']['Close']();
}

export function DeleteStoredAdoptionConfiguration(arg1) {
  return window['go']['main']['ManagerAPI']['DeleteStoredAdoptionConfiguration'](arg1);
}

export function DeleteStoredScript(arg1) {
  return window['go']['main']['ManagerAPI']['DeleteStoredScript'](arg1);
}

export function ForwardFrame(arg1, arg2) {
  return window['go']['main']['ManagerAPI']['ForwardFrame'](arg1, arg2);
}

export function GetAdoptedIPAddressDetails(arg1) {
  return window['go']['main']['ManagerAPI']['GetAdoptedIPAddressDetails'](arg1);
}

export function GetStoredScript(arg1) {
  return window['go']['main']['ManagerAPI']['GetStoredScript'](arg1);
}

export function ListAdoptedIPAddresses() {
  return window['go']['main']['ManagerAPI']['ListAdoptedIPAddresses']();
}

export function ListStoredAdoptionConfigurations() {
  return window['go']['main']['ManagerAPI']['ListStoredAdoptionConfigurations']();
}

export function ListStoredScripts() {
  return window['go']['main']['ManagerAPI']['ListStoredScripts']();
}

export function RefreshStoredScripts() {
  return window['go']['main']['ManagerAPI']['RefreshStoredScripts']();
}

export function ReleaseIPAddress(arg1) {
  return window['go']['main']['ManagerAPI']['ReleaseIPAddress'](arg1);
}

export function ResolveDNSAdoptedIPAddress(arg1) {
  return window['go']['main']['ManagerAPI']['ResolveDNSAdoptedIPAddress'](arg1);
}

export function SaveStoredAdoptionConfiguration(arg1) {
  return window['go']['main']['ManagerAPI']['SaveStoredAdoptionConfiguration'](arg1);
}

export function SaveStoredScript(arg1) {
  return window['go']['main']['ManagerAPI']['SaveStoredScript'](arg1);
}

export function StartAdoptedIPAddressRecording(arg1, arg2) {
  return window['go']['main']['ManagerAPI']['StartAdoptedIPAddressRecording'](arg1, arg2);
}

export function StartAdoptedIPAddressService(arg1, arg2, arg3) {
  return window['go']['main']['ManagerAPI']['StartAdoptedIPAddressService'](arg1, arg2, arg3);
}

export function StopAdoptedIPAddressRecording(arg1) {
  return window['go']['main']['ManagerAPI']['StopAdoptedIPAddressRecording'](arg1);
}

export function StopAdoptedIPAddressService(arg1, arg2) {
  return window['go']['main']['ManagerAPI']['StopAdoptedIPAddressService'](arg1, arg2);
}

export function UpdateAdoptedIPAddressMTU(arg1, arg2) {
  return window['go']['main']['ManagerAPI']['UpdateAdoptedIPAddressMTU'](arg1, arg2);
}

export function UpdateAdoptedIPAddressScripts(arg1, arg2, arg3) {
  return window['go']['main']['ManagerAPI']['UpdateAdoptedIPAddressScripts'](arg1, arg2, arg3);
}
